apiVersion: v1
kind: Service
metadata:
  name: balance-service  
spec:
  selector:
    app: balance-service
    tier: backend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: grpc
    port: 50051
    targetPort: 50051
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-service
  labels: 
    app: balance-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balance-service
      tier: backend
  template:
    metadata:
      labels:
        app: balance-service
        tier: backend  
    spec:                 
      containers: 
      - name: balance-service 
        image: rogeroriol/balance-service:latest
        env:
          - name: PORT
            value: "8080"
          - name: MONGO_URL
            value: balanceservice-mongo:27017
          - name: MONGO_DATABASE
            value: admin
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: balanceservice-mongo-root-credentials
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: balanceservice-mongo-root-credentials
                key: password
          - name: MONGO_RETRIES
            value: "8"
        ports:
        - containerPort: 8080
        - containerPort: 50051
