apiVersion: v1
kind: Service
metadata:
  name: event-service  
spec:
  selector:
    app: event-service
    tier: backend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  labels: 
    app: event-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
      tier: backend
  template:
    metadata:
      labels:
        app: event-service
        tier: backend  
    spec:                 
      containers: 
      - name: event-service 
        image: rogeroriol/event-service:latest
        env:
          - name: MONGO_URL
            value: mongodb://eventservice-mongo:27017/events
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: eventservice-mongo-root-credentials
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: eventservice-mongo-root-credentials
                key: password
          - name: MONGO_RETRIES
            value: "8"
          - name: SQS_URL
            value: https://sqs.eu-west-1.amazonaws.com/725226204633/tfg-queue
        ports:
        - containerPort: 8080