// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: protos/balance-service.proto

package balance_service

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CashBetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId *string  `protobuf:"bytes,1,req,name=userId" json:"userId,omitempty"`
	Prize  *float32 `protobuf:"fixed32,2,req,name=prize" json:"prize,omitempty"`
}

func (x *CashBetRequest) Reset() {
	*x = CashBetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_balance_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CashBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashBetRequest) ProtoMessage() {}

func (x *CashBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_balance_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashBetRequest.ProtoReflect.Descriptor instead.
func (*CashBetRequest) Descriptor() ([]byte, []int) {
	return file_protos_balance_service_proto_rawDescGZIP(), []int{0}
}

func (x *CashBetRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *CashBetRequest) GetPrize() float32 {
	if x != nil && x.Prize != nil {
		return *x.Prize
	}
	return 0
}

type CashBetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK *bool `protobuf:"varint,1,req,name=OK" json:"OK,omitempty"`
}

func (x *CashBetResponse) Reset() {
	*x = CashBetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_balance_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CashBetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashBetResponse) ProtoMessage() {}

func (x *CashBetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_balance_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashBetResponse.ProtoReflect.Descriptor instead.
func (*CashBetResponse) Descriptor() ([]byte, []int) {
	return file_protos_balance_service_proto_rawDescGZIP(), []int{1}
}

func (x *CashBetResponse) GetOK() bool {
	if x != nil && x.OK != nil {
		return *x.OK
	}
	return false
}

type PayBetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId *string  `protobuf:"bytes,1,req,name=userId" json:"userId,omitempty"`
	Amount *float32 `protobuf:"fixed32,2,req,name=amount" json:"amount,omitempty"`
}

func (x *PayBetRequest) Reset() {
	*x = PayBetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_balance_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayBetRequest) ProtoMessage() {}

func (x *PayBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_balance_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayBetRequest.ProtoReflect.Descriptor instead.
func (*PayBetRequest) Descriptor() ([]byte, []int) {
	return file_protos_balance_service_proto_rawDescGZIP(), []int{2}
}

func (x *PayBetRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *PayBetRequest) GetAmount() float32 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

type PayBetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK *bool `protobuf:"varint,1,req,name=OK" json:"OK,omitempty"`
}

func (x *PayBetResponse) Reset() {
	*x = PayBetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_balance_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayBetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayBetResponse) ProtoMessage() {}

func (x *PayBetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_balance_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayBetResponse.ProtoReflect.Descriptor instead.
func (*PayBetResponse) Descriptor() ([]byte, []int) {
	return file_protos_balance_service_proto_rawDescGZIP(), []int{3}
}

func (x *PayBetResponse) GetOK() bool {
	if x != nil && x.OK != nil {
		return *x.OK
	}
	return false
}

var File_protos_balance_service_proto protoreflect.FileDescriptor

var file_protos_balance_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e,
	0x0a, 0x0e, 0x43, 0x61, 0x73, 0x68, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x7a, 0x65, 0x22, 0x21,
	0x0a, 0x0f, 0x43, 0x61, 0x73, 0x68, 0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x4b, 0x18, 0x01, 0x20, 0x02, 0x28, 0x08, 0x52, 0x02, 0x4f,
	0x4b, 0x22, 0x3f, 0x0a, 0x0d, 0x50, 0x61, 0x79, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x20, 0x0a, 0x0e, 0x50, 0x61, 0x79, 0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x4b, 0x18, 0x01, 0x20, 0x02, 0x28, 0x08,
	0x52, 0x02, 0x4f, 0x4b, 0x32, 0x69, 0x0a, 0x0e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x43, 0x61, 0x73, 0x68, 0x42, 0x65,
	0x74, 0x12, 0x0f, 0x2e, 0x43, 0x61, 0x73, 0x68, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x43, 0x61, 0x73, 0x68, 0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x50, 0x61, 0x79, 0x42, 0x65, 0x74, 0x12, 0x0e,
	0x2e, 0x50, 0x61, 0x79, 0x42, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f,
	0x2e, 0x50, 0x61, 0x79, 0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
}

var (
	file_protos_balance_service_proto_rawDescOnce sync.Once
	file_protos_balance_service_proto_rawDescData = file_protos_balance_service_proto_rawDesc
)

func file_protos_balance_service_proto_rawDescGZIP() []byte {
	file_protos_balance_service_proto_rawDescOnce.Do(func() {
		file_protos_balance_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_balance_service_proto_rawDescData)
	})
	return file_protos_balance_service_proto_rawDescData
}

var file_protos_balance_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_balance_service_proto_goTypes = []interface{}{
	(*CashBetRequest)(nil),  // 0: CashBetRequest
	(*CashBetResponse)(nil), // 1: CashBetResponse
	(*PayBetRequest)(nil),   // 2: PayBetRequest
	(*PayBetResponse)(nil),  // 3: PayBetResponse
}
var file_protos_balance_service_proto_depIdxs = []int32{
	0, // 0: BalanceService.CashBet:input_type -> CashBetRequest
	2, // 1: BalanceService.PayBet:input_type -> PayBetRequest
	1, // 2: BalanceService.CashBet:output_type -> CashBetResponse
	3, // 3: BalanceService.PayBet:output_type -> PayBetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_balance_service_proto_init() }
func file_protos_balance_service_proto_init() {
	if File_protos_balance_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_balance_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CashBetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_balance_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CashBetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_balance_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayBetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_balance_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayBetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_balance_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_balance_service_proto_goTypes,
		DependencyIndexes: file_protos_balance_service_proto_depIdxs,
		MessageInfos:      file_protos_balance_service_proto_msgTypes,
	}.Build()
	File_protos_balance_service_proto = out.File
	file_protos_balance_service_proto_rawDesc = nil
	file_protos_balance_service_proto_goTypes = nil
	file_protos_balance_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BalanceServiceClient is the client API for BalanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BalanceServiceClient interface {
	CashBet(ctx context.Context, in *CashBetRequest, opts ...grpc.CallOption) (*CashBetResponse, error)
	PayBet(ctx context.Context, in *PayBetRequest, opts ...grpc.CallOption) (*PayBetResponse, error)
}

type balanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBalanceServiceClient(cc grpc.ClientConnInterface) BalanceServiceClient {
	return &balanceServiceClient{cc}
}

func (c *balanceServiceClient) CashBet(ctx context.Context, in *CashBetRequest, opts ...grpc.CallOption) (*CashBetResponse, error) {
	out := new(CashBetResponse)
	err := c.cc.Invoke(ctx, "/BalanceService/CashBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceServiceClient) PayBet(ctx context.Context, in *PayBetRequest, opts ...grpc.CallOption) (*PayBetResponse, error) {
	out := new(PayBetResponse)
	err := c.cc.Invoke(ctx, "/BalanceService/PayBet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceServiceServer is the server API for BalanceService service.
type BalanceServiceServer interface {
	CashBet(context.Context, *CashBetRequest) (*CashBetResponse, error)
	PayBet(context.Context, *PayBetRequest) (*PayBetResponse, error)
}

// UnimplementedBalanceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBalanceServiceServer struct {
}

func (*UnimplementedBalanceServiceServer) CashBet(context.Context, *CashBetRequest) (*CashBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CashBet not implemented")
}
func (*UnimplementedBalanceServiceServer) PayBet(context.Context, *PayBetRequest) (*PayBetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayBet not implemented")
}

func RegisterBalanceServiceServer(s *grpc.Server, srv BalanceServiceServer) {
	s.RegisterService(&_BalanceService_serviceDesc, srv)
}

func _BalanceService_CashBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CashBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServiceServer).CashBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BalanceService/CashBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServiceServer).CashBet(ctx, req.(*CashBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceService_PayBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServiceServer).PayBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BalanceService/PayBet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServiceServer).PayBet(ctx, req.(*PayBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BalanceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BalanceService",
	HandlerType: (*BalanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CashBet",
			Handler:    _BalanceService_CashBet_Handler,
		},
		{
			MethodName: "PayBet",
			Handler:    _BalanceService_PayBet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/balance-service.proto",
}
