apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfg-web-server-deployment
spec:
  selector:
    matchLabels:
      app: tfg-web-server
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: tfg-web-server
    spec:
      containers:
        - image: rogeroriol/tfg-web-server
          name: tfg-web-server
          ports:
            - containerPort: 80
