apiVersion: v1
kind: Service
metadata:
  name: liveresult-service  
spec:
  selector:
    app: liveresult-service
    tier: backend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: grpc
    port: 50051
    targetPort: 50051
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveresult-service
  labels: 
    app: liveresult-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveresult-service
      tier: backend
  template:
    metadata:
      labels:
        app: liveresult-service
        tier: backend  
    spec:                 
      containers: 
      - name: liveresult-service 
        image: rogeroriol/live-result-service:latest
        ports:
        - containerPort: 8080
        - containerPort: 50051
