apiVersion: v1
kind: Service
metadata:
  name: liveresult-service  
spec:
  selector:
    app: liveresult-service
    tier: backend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
    name: http
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveresult-service
  labels: 
    app: liveresult-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveresult-service
      tier: backend
  template:
    metadata:
      labels:
        app: liveresult-service
        tier: backend  
    spec:                 
      containers: 
      - name: liveresult-service 
        image: rogeroriol/liveresult-service:latest
        env:
          - name: MONGO_URL
            value: liveresult-mongo:27017
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: liveresult-mongo-root-credentials
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: liveresult-mongo-root-credentials
                key: password
          - name: MONGO_RETRIES
            value: "8"
        ports:
        - containerPort: 8080