apiVersion: v1
kind: Service
metadata:
  labels:
    app: oddsservice-mongo
    tier: database
  name: oddsservice-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: oddsservice-mongo
    tier: database
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odds-mongo-pv-claim
  labels:
    app: oddsservice-mongo
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oddsservice-mongo
  labels:
    app: oddsservice-mongo
    tier: database
spec:
  selector:
    matchLabels:
      app: oddsservice-mongo
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oddsservice-mongo
        tier: database
    spec:
      containers:
      - image: mongo:4.2.1
        name: oddsservice-mongo
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: oddsservice-mongo-root-credentials
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: oddsservice-mongo-root-credentials
                key: password
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: odds-mongo-pv-claim
